### ISSUE TITLE
Object [object Object] has no method 'retrieveJsMessages' at file:///android_asset/www/cordova.js:960:38

### ISSUE THREAD

**Issue by grassick** [mWater/app-v3#468]
```
 "device": "{\"available\":true,\"platform\":\"Android\",\"version\":\"4.4.2\",\"uuid\":\"d0eaf4b4208118ce\",\"cordova\":\"3.6.4\",\"model\":\"surtab7 3GS\",\"manufacturer\":\"alps\"}",
```

**Comment by grassick** [comment]
Tons of people are having this.

```
window.onerror:window.onerror: Uncaught TypeError: Object [object Object] has no method 'retrieveJsMessages' at file:///android_asset/www/cordova.js:955:22\nTypeError: Object [object Object] has no method 'retrieveJsMessages'\n    at pollOnce (file:///android_asset/www/cordova.js:960:39)\n    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:951:5)",
```
