### ISSUE TITLE
Script errors on Internet Explorer 11

### ISSUE THREAD

**Issue by grassick** [mWater/app-v3#471]
```
  "user_agent": "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; BRI/2; MALNJS; rv:11.0) like Gecko",
  "log": "log: Loading at: http://app.mwater.co/\r\nlog: {\"name\":\"Internet Explorer\",\"msie\":true,\"version\":\"11.0\",\"tablet\":true,\"a\":true}\r\nlog: Selecting LocalStorageDb for fallback\r\nlog: Getting location\r\nlog: Starting location watch 4\r\nlog: Opened page undefined (undefined)\r\nlog: Reporting problem...\r\nlog: Reporting problem...",
  "desc": "window.onerror:window.onerror: No such interface supported\r\n at http://app.mwater.co/js/libs.js:9:16005\nError: No such interface supported\r\n\n   at _removeIcon (http://app.mwater.co/js/libs.js:9:16005)\n   at onRemove (http://app.mwater.co/js/libs.js:9:14452)\n   at removeLayer (http://app.mwater.co/js/libs.js:8:21518)\n   at eachLayer (http://app.mwater.co/js/libs.js:9:25701)\n  
```

**Comment by grassick** [comment]
Unpatched IE 11 problem
